## Preprocessing

In [1]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [3]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
application_cl_df = application_df.drop(["EIN","NAME"],axis=1)
application_cl_df.head()

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [4]:
# Determine the number of unique values in each column.
dataframe_count = application_cl_df.dtypes.index.tolist()
application_df[dataframe_count].nunique()

APPLICATION_TYPE            17
AFFILIATION                  6
CLASSIFICATION              71
USE_CASE                     5
ORGANIZATION                 4
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
dtype: int64

In [5]:
# Look at APPLICATION_TYPE value counts for binning
df_type_count = application_cl_df['APPLICATION_TYPE'].value_counts()
df_type_count

APPLICATION_TYPE
T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: count, dtype: int64

In [6]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
application_types_to_replace = list(df_type_count[df_type_count < 600].index)

# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure binning was successful
application_df['APPLICATION_TYPE'].value_counts()

APPLICATION_TYPE
T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
Other      804
T8         737
T7         725
Name: count, dtype: int64

In [7]:
# Look at CLASSIFICATION value counts for binning
class_count = application_cl_df['CLASSIFICATION'].value_counts()
class_count.head(10)

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
Name: count, dtype: int64

In [8]:
# You may find it helpful to look at CLASSIFICATION value counts >1
application_cl_df['CLASSIFICATION'].value_counts().loc[lambda x : x >1]

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: count, dtype: int64

In [9]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
classifications_to_replace = list(class_count[class_count < 300].index)

# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")

# Check to make sure binning was successful
application_df['CLASSIFICATION'].value_counts()

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
Other     1484
C7000      777
Name: count, dtype: int64

In [10]:
# Convert categorical data to numeric with `pd.get_dummies`
application_dummies = pd.get_dummies(application_cl_df)
application_dummies.head()

,STATUS,ASK_AMT,IS_SUCCESSFUL,APPLICATION_TYPE_T10,APPLICATION_TYPE_T12,APPLICATION_TYPE_T13,APPLICATION_TYPE_T14,APPLICATION_TYPE_T15,APPLICATION_TYPE_T17,APPLICATION_TYPE_T19,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,True,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
1,1,108590,1,False,False,False,False,False,False,False,...,True,False,False,False,False,False,False,False,True,False
2,1,5000,0,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
3,1,6692,1,False,False,False,False,False,False,False,...,False,True,False,False,False,False,False,False,True,False
4,1,142590,1,False,False,False,False,False,False,False,...,False,False,True,False,False,False,False,False,True,False

In [11]:
# Split our preprocessed data into our features and target arrays
y = application_dummies['IS_SUCCESSFUL'].values
X = application_dummies.drop('IS_SUCCESSFUL', axis=1).values

# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=78)

In [12]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Compile, Train and Evaluate the Model

In [13]:
# ----- FIRST TRY ------


# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
number_input_features = len(X_train_scaled[0])
hidden_nodes_layer1 = 10
hidden_nodes_layer2 = 20

nn_model = tf.keras.models.Sequential()

# First hidden layer
nn_model.add(tf.keras.layers.Dense(units=hidden_nodes_layer1,
             input_dim=number_input_features, activation="tanh"))

# Second hidden layer
nn_model.add(tf.keras.layers.Dense(
    units=hidden_nodes_layer2, activation="sigmoid"))

# Output layer
nn_model.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Check the structure of the model
nn_model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 10)                1170

 dense_1 (Dense)             (None, 20)                220

 dense_2 (Dense)             (None, 1)                 21

=================================================================
Total params: 1411 (5.51 KB)
Trainable params: 1411 (5.51 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [14]:
# Compile the model
nn_model.compile(loss = 'binary_crossentropy', optimizer = 'adam', metrics=['accuracy'])

In [15]:
# Train the model
fit_model = nn_model.fit(X_train_scaled, y_train, epochs=25)

Epoch 1/25
804/804 [==============================] - 2s 2ms/step - loss: 0.6279 - accuracy: 0.6745
Epoch 2/25
804/804 [==============================] - 1s 2ms/step - loss: 0.5696 - accuracy: 0.7239
Epoch 3/25
804/804 [==============================] - 2s 2ms/step - loss: 0.5618 - accuracy: 0.7292
Epoch 4/25
804/804 [==============================] - 2s 2ms/step - loss: 0.5565 - accuracy: 0.7307
Epoch 5/25
804/804 [==============================] - 2s 2ms/step - loss: 0.5533 - accuracy: 0.7320
Epoch 6/25
804/804 [==============================] - 1s 2ms/step - loss: 0.5516 - accuracy: 0.7332
Epoch 7/25
804/804 [==============================] - 1s 2ms/step - loss: 0.5504 - accuracy: 0.7329
Epoch 8/25
804/804 [==============================] - 1s 2ms/step - loss: 0.5493 - accuracy: 0.7334
Epoch 9/25
804/804 [==============================] - 1s 2ms/step - loss: 0.5483 - accuracy: 0.7329
Epoch 10/25
804/804 [==============================] - 1s 2ms/step - loss: 0.5477 - accuracy: 0.7329
Epoch 11/25
804/804 [==============================] - 1s 2ms/step - loss: 0.5468 - accuracy: 0.7345
Epoch 12/25
804/804 [==============================] - 1s 2ms/step - loss: 0.5464 - accuracy: 0.7341
Epoch 13/25
804/804 [==============================] - 2s 2ms/step - loss: 0.5455 - accuracy: 0.7348
Epoch 14/25
804/804 [==============================] - 2s 2ms/step - loss: 0.5454 - accuracy: 0.7350
Epoch 15/25
804/804 [==============================] - 1s 2ms/step - loss: 0.5449 - accuracy: 0.7352
Epoch 16/25
804/804 [==============================] - 1s 2ms/step - loss: 0.5444 - accuracy: 0.7353
Epoch 17/25
804/804 [==============================] - 1s 2ms/step - loss: 0.5438 - accuracy: 0.7347
Epoch 18/25
804/804 [==============================] - 1s 2ms/step - loss: 0.5433 - accuracy: 0.7355
Epoch 19/25
804/804 [==============================] - 1s 2ms/step - loss: 0.5432 - accuracy: 0.7357
Epoch 20/25
804/804 [==============================] - 1s 2ms/step - loss: 0.5427 - accuracy: 0.7364
Epoch 21/25
804/804 [==============================] - 1s 2ms/step - loss: 0.5426 - accuracy: 0.7370
Epoch 22/25
804/804 [==============================] - 2s 2ms/step - loss: 0.5423 - accuracy: 0.7356
Epoch 23/25
804/804 [==============================] - 2s 3ms/step - loss: 0.5416 - accuracy: 0.7365
Epoch 24/25
804/804 [==============================] - 1s 2ms/step - loss: 0.5416 - accuracy: 0.7369
Epoch 25/25
804/804 [==============================] - 1s 2ms/step - loss: 0.5414 - accuracy: 0.7368

In [17]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn_model.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 0s - loss: 0.5525 - accuracy: 0.7261 - 425ms/epoch - 2ms/step
Loss: 0.5525009632110596, Accuracy: 0.726064145565033

In [18]:
# Export our model to HDF5 file
nn_model.save('AlphabetSoupCharity_Optimization1.h5')

/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(

In [25]:
# ----- SECOND TRY -----

# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
number_input_features = len(X_train_scaled[0])
hidden_nodes_layer1 = 15
hidden_nodes_layer2 = 25
hidden_nodes_layer3 = 25
nn_model = tf.keras.models.Sequential()

In [20]:
# First hidden layer
nn_model.add(tf.keras.layers.Dense(units=hidden_nodes_layer1,
             input_dim=number_input_features, activation="tanh"))

# Second hidden layer
nn_model.add(tf.keras.layers.Dense(
    units=hidden_nodes_layer2, activation="sigmoid"))

# 3rd hidden layer
nn_model.add(tf.keras.layers.Dense(
    units=hidden_nodes_layer3, activation="relu"))

# Output layer
nn_model.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Check the structure of the model
nn_model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_3 (Dense)             (None, 15)                1755

 dense_4 (Dense)             (None, 25)                400

 dense_5 (Dense)             (None, 25)                650

 dense_6 (Dense)             (None, 1)                 26

=================================================================
Total params: 2831 (11.06 KB)
Trainable params: 2831 (11.06 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [21]:
# Compile the model
nn_model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [22]:
# Train the model
fit_model = nn_model.fit(X_train_scaled, y_train, epochs=25)

Epoch 1/25
804/804 [==============================] - 2s 2ms/step - loss: 0.5866 - accuracy: 0.7092
Epoch 2/25
804/804 [==============================] - 1s 2ms/step - loss: 0.5565 - accuracy: 0.7306
Epoch 3/25
804/804 [==============================] - 2s 2ms/step - loss: 0.5519 - accuracy: 0.7313
Epoch 4/25
804/804 [==============================] - 2s 2ms/step - loss: 0.5493 - accuracy: 0.7324
Epoch 5/25
804/804 [==============================] - 2s 3ms/step - loss: 0.5471 - accuracy: 0.7328
Epoch 6/25
804/804 [==============================] - 2s 2ms/step - loss: 0.5466 - accuracy: 0.7340
Epoch 7/25
804/804 [==============================] - 1s 2ms/step - loss: 0.5458 - accuracy: 0.7326
Epoch 8/25
804/804 [==============================] - 1s 2ms/step - loss: 0.5455 - accuracy: 0.7344
Epoch 9/25
804/804 [==============================] - 1s 2ms/step - loss: 0.5446 - accuracy: 0.7345
Epoch 10/25
804/804 [==============================] - 1s 2ms/step - loss: 0.5438 - accuracy: 0.7345
Epoch 11/25
804/804 [==============================] - 1s 2ms/step - loss: 0.5435 - accuracy: 0.7352
Epoch 12/25
804/804 [==============================] - 1s 2ms/step - loss: 0.5431 - accuracy: 0.7354
Epoch 13/25
804/804 [==============================] - 2s 3ms/step - loss: 0.5428 - accuracy: 0.7353
Epoch 14/25
804/804 [==============================] - 2s 3ms/step - loss: 0.5426 - accuracy: 0.7351
Epoch 15/25
804/804 [==============================] - 1s 2ms/step - loss: 0.5422 - accuracy: 0.7370
Epoch 16/25
804/804 [==============================] - 1s 2ms/step - loss: 0.5421 - accuracy: 0.7362
Epoch 17/25
804/804 [==============================] - 1s 2ms/step - loss: 0.5416 - accuracy: 0.7367
Epoch 18/25
804/804 [==============================] - 1s 2ms/step - loss: 0.5417 - accuracy: 0.7356
Epoch 19/25
804/804 [==============================] - 1s 2ms/step - loss: 0.5412 - accuracy: 0.7359
Epoch 20/25
804/804 [==============================] - 1s 2ms/step - loss: 0.5407 - accuracy: 0.7369
Epoch 21/25
804/804 [==============================] - 1s 2ms/step - loss: 0.5411 - accuracy: 0.7362
Epoch 22/25
804/804 [==============================] - 2s 3ms/step - loss: 0.5403 - accuracy: 0.7358
Epoch 23/25
804/804 [==============================] - 2s 2ms/step - loss: 0.5401 - accuracy: 0.7369
Epoch 24/25
804/804 [==============================] - 1s 2ms/step - loss: 0.5400 - accuracy: 0.7369
Epoch 25/25
804/804 [==============================] - 1s 2ms/step - loss: 0.5397 - accuracy: 0.7376

In [23]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn_model.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 1s - loss: 0.5528 - accuracy: 0.7250 - 1s/epoch - 4ms/step
Loss: 0.5527626872062683, Accuracy: 0.7250145673751831

In [24]:
# Export our model to HDF5 file
nn_model.save('AlphabetSoupCharity_Optimization2.h5')

In [26]:
# ----- THIRD TRY -----

# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
number_input_features = len(X_train_scaled[0])
hidden_nodes_layer1 = 30
hidden_nodes_layer2 = 25
hidden_nodes_layer3 = 20
nn_model = tf.keras.models.Sequential()

In [27]:
# First hidden layer
nn_model.add(tf.keras.layers.Dense(units=hidden_nodes_layer1,
             input_dim=number_input_features, activation="tanh"))

# Second hidden layer
nn_model.add(tf.keras.layers.Dense(
    units=hidden_nodes_layer2, activation="sigmoid"))

# 3rd hidden layer
nn_model.add(tf.keras.layers.Dense(
    units=hidden_nodes_layer3, activation="sigmoid"))

# Output layer
nn_model.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Check the structure of the model
nn_model.summary()

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_7 (Dense)             (None, 30)                3510

 dense_8 (Dense)             (None, 25)                775

 dense_9 (Dense)             (None, 20)                520

 dense_10 (Dense)            (None, 1)                 21

=================================================================
Total params: 4826 (18.85 KB)
Trainable params: 4826 (18.85 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [28]:
# Compile the model
nn_model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [29]:
# Train the model
fit_model = nn_model.fit(X_train_scaled, y_train, epochs=25)

Epoch 1/25
804/804 [==============================] - 3s 2ms/step - loss: 0.5894 - accuracy: 0.7103
Epoch 2/25
804/804 [==============================] - 2s 3ms/step - loss: 0.5615 - accuracy: 0.7310
Epoch 3/25
804/804 [==============================] - 2s 2ms/step - loss: 0.5550 - accuracy: 0.7323
Epoch 4/25
804/804 [==============================] - 2s 2ms/step - loss: 0.5518 - accuracy: 0.7334
Epoch 5/25
804/804 [==============================] - 2s 2ms/step - loss: 0.5495 - accuracy: 0.7344
Epoch 6/25
804/804 [==============================] - 1s 2ms/step - loss: 0.5480 - accuracy: 0.7350
Epoch 7/25
804/804 [==============================] - 1s 2ms/step - loss: 0.5472 - accuracy: 0.7349
Epoch 8/25
804/804 [==============================] - 1s 2ms/step - loss: 0.5456 - accuracy: 0.7355
Epoch 9/25
804/804 [==============================] - 2s 2ms/step - loss: 0.5449 - accuracy: 0.7360
Epoch 10/25
804/804 [==============================] - 2s 3ms/step - loss: 0.5441 - accuracy: 0.7357
Epoch 11/25
804/804 [==============================] - 2s 2ms/step - loss: 0.5432 - accuracy: 0.7362
Epoch 12/25
804/804 [==============================] - 1s 2ms/step - loss: 0.5428 - accuracy: 0.7360
Epoch 13/25
804/804 [==============================] - 1s 2ms/step - loss: 0.5419 - accuracy: 0.7366
Epoch 14/25
804/804 [==============================] - 1s 2ms/step - loss: 0.5418 - accuracy: 0.7367
Epoch 15/25
804/804 [==============================] - 1s 2ms/step - loss: 0.5411 - accuracy: 0.7368
Epoch 16/25
804/804 [==============================] - 1s 2ms/step - loss: 0.5408 - accuracy: 0.7375
Epoch 17/25
804/804 [==============================] - 1s 2ms/step - loss: 0.5407 - accuracy: 0.7362
Epoch 18/25
804/804 [==============================] - 2s 2ms/step - loss: 0.5402 - accuracy: 0.7376
Epoch 19/25
804/804 [==============================] - 2s 3ms/step - loss: 0.5399 - accuracy: 0.7375
Epoch 20/25
804/804 [==============================] - 2s 2ms/step - loss: 0.5397 - accuracy: 0.7364
Epoch 21/25
804/804 [==============================] - 1s 2ms/step - loss: 0.5394 - accuracy: 0.7380
Epoch 22/25
804/804 [==============================] - 1s 2ms/step - loss: 0.5387 - accuracy: 0.7390
Epoch 23/25
804/804 [==============================] - 1s 2ms/step - loss: 0.5388 - accuracy: 0.7375
Epoch 24/25
804/804 [==============================] - 1s 2ms/step - loss: 0.5380 - accuracy: 0.7386
Epoch 25/25
804/804 [==============================] - 1s 2ms/step - loss: 0.5383 - accuracy: 0.7391

In [30]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn_model.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 0s - loss: 0.5524 - accuracy: 0.7258 - 424ms/epoch - 2ms/step
Loss: 0.5523659586906433, Accuracy: 0.7258309125900269

In [31]:
# Export our model to HDF5 file
nn_model.save('AlphabetSoupCharity_Optimization3.h5')